services:
  db:
    image: mysql:lts
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: slaptazodis
      MYSQL_DATABASE: mydb
      MYSQL_USER: vartotojas
      MYSQL_PASSWORD: slaptazodis
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    image: node:lts-alpine
    restart: always
    working_dir: /app
    volumes:
      - ./api:/app
    command: sh -c 'npm i --no-audit && npm start'
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: vartotojas
      MYSQL_PASSWORD: slaptazodis
      MYSQL_DBNAME: mydb
      MYSQL_PORT: 3306
      PORT: 3000
      CHOKIDAR_USEPOLLING: true

  front:
    image: node:lts-alpine
    restart: always
    working_dir: /app
    volumes:
      - ./front:/app
    command: sh -c 'npm i --no-audit && npm run dev'
    # ports:
    #   - "80:80"
    depends_on:
      - api

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: slaptazodis
    depends_on:
      - db

  admin:
    image: node:lts-alpine
    restart: always
    working_dir: /app
    ports:
      - 81:81
    volumes:
      - ./admin:/app
    command: sh -c 'npm i --no-audit && npm run dev'
    depends_on:
      - api

volumes:
  db_data:
